### ISSUE TITLE
Destroy scripts don't work

### ISSUE THREAD

**Issue by aggravateexe** [Tundra-Editor/Issues#41] opened 2023-04-04 21:16 UTC
**Describe the bug**
The scripts DestroyObjects and DestroyOnCheckpointRestart do not destroy objects ever since the Addressable update.
I haven't tested the other destroy scripts, but I have a feeling they also don't work.

**To Reproduce**
1. Apply either DestroyObjects or DestroyOnCheckpointRestart onto a game object.
2. Activate each scripts with a trigger or event.

**Expected behavior**
Both scripts are supposed to delete the objects desired when their conditions have met.

**General (please complete the following information):**
 - OS: Windows 10

**Editor (please complete the following information if editor-related):**
 - Unity [e.g. 2019.4.40f1]
 - Enough disk space: [Yes]
 - Up to date: [Yes]

**Game (please complete the following information if game-related):**
 - Agony [2023.4.1]

**Comment by PITR-DEV** [comment] 2023-05-01 20:38
Looks to be a duplicate of #37

**Closed by PITR-DEV** 2023-05-01 20:38 UTC
Labels: bug
