### ISSUE TITLE
FirstRoom Pit crashes the game

### ISSUE THREAD

**Issue by RobiFox** [Tundra-Editor/Issues#28] opened 2023-03-21 23:27 UTC
**Describe the bug**
Loading a level that uses FirstRoom Pit crashes the game.

**To Reproduce**
1. Create a level
2. Replace FirstRoom with FirstRoom Pit
3. Export and load level

**Expected behavior**
For the level to load fine and not crash

**General (please complete the following information):**
 - OS: [Windows 10]

**Editor (please complete the following information if editor-related):**
 - Unity [2019.4.16f1]
 - Enough disk space: [Yes]
 - Up to date: [Yes]

**Game (please complete the following information if game-related):**
 - Agony [31]

**Comment by PITR-DEV** [comment] 2023-03-22 02:14
@RobiFox Can you check what's the path of the FirstRoom Pit prefab you are using?
It doesn't crash on my end, and earlier, a broken duplicate of all the first rooms was included as well.

**Comment by RobiFox** [comment] 2023-03-22 10:40
I use `Auto Prefabs/FirstRoom Pit`. I tried updating to the newer prefabs, but nothing changed
I attached a ZIP file of the .blood and .unity file that crashes the game
[testy test.zip](https://github.com/Tundra-Editor/Issues/files/11039097/testy.test.zip)

**Comment by PITR-DEV** [comment] 2023-03-22 23:29
I was able to reproduce this issue in agony 31, and I am no longer able to reproduce it in newer builds.
I'll close the issue for now.
Please reopen it, if the problem persist for you in agony 32

**Comment by PITR-DEV** [comment] 2023-03-23 02:28
The issue appears to only happen in builds from Steam

**Comment by PITR-DEV** [comment] 2023-03-24 21:10
![image](https://user-images.githubusercontent.com/13086471/227642232-a1a549a7-0c4c-43da-b091-c9ff21ce4c8d.png)
Unequipping the freezeframe rocket launcher should work as a workaround for now.

**Closed** 2023-03-30 18:54 UTC
Labels: bug
